### ISSUE TITLE
ResponseMatcher.java:38-42: There are a lot of `AllOf<>`...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#129]
The puzzle `119-d2c675f4` from #119 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/942d4e6ac5972ec0bf138fa608117d912f9bbc27/src/test/java/com/artipie/docker/http/ResponseMatcher.java#L38-L42

The puzzle was created by @olenagerasimova on 20-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olegmoz** [comment]
@olenagerasimova would you like to take on this issue?

**Comment by olenagerasimova** [comment]
@olegmoz yes, assign me please

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olenagerasimova** [comment]
@olegmoz I've been thinking about `com.artipie.docker.http.ResponseMatcher` class and it seems that this class is not a good idea because it hides expected statutes/headers/whatever and makes assertion not transparent. In my opinion each assert statement in test methods should be clear, fully visible (on the screen, so we don't have to navigate somewhere to check what is expected) and transparent, some code duplication in expected part of the assertion is absolutely ok and should be left as is for assertion's fullness sake.
Thus I'd suggest getting rid of `com.artipie.docker.http.ResponseMatcher` and use `ResponseMatcher` from http to avoid `Matcher.allOf<>(new ListOf<>(...))` constant creation, all expected headers and statuses will be present right in the assertion.
What do you say?

**Comment by olegmoz** [comment]
@olenagerasimova I think you are right and `com.artipie.docker.http.ResponseMatcher` is not needed as it is, but I'd replace it with private matcher classes for GET and HEAD responses in `ManifestEntityGetTest` and `ManifestEntityHeadTest` respectively.

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
